/**
 * NPC (AI fish) display names. Edit this list to change the pool of names
 * randomly assigned to AI fish. Names are de-duplicated implicitly by the
 * spawner's "avoid taken names" logic, but keep the list itself unique to
 * avoid skewing the random distribution.
 *
 * See `pickAiName` in `ai.ts` for how these are assigned (humans get priority
 * over AI for any colliding name).
 */
export const NPC_NAMES = [
  "Keys",
  "Nully",
  "Tuna",
  "NitroG",
  "Sybex",
  "Sky King",
  "Mortal6",
  "Flow",
  "Baezil",
  "So1ician",
  "Alexa2",
  "Strawberry",
  "Belsarion",
  "Cody",
  "Forkman",
  "Jebus",
  "LateNightTacos",
  "LemonChicken",
  "MacDaddysBigDong",
  "mikado",
  "morph",
  "Pdwhite",
  "LeelooLoves",
  "SleepyMichael",
  "Tomato",
  "zen",
  "Zup",
  "Nemesis",
  "Beka-Exandria",
  "Exander",
  "Bongs",
  "Caelifera",
  "Camanda",
  "Casoph",
  "CBA",
  "CrackerCarl",
  "Ctp",
  "cwis",
  "Dan",
  "dino",
  "Dung Heaver",
  "Dyruss",
  "Executioner",
  "Fish",
  "Five10",
  "Flikk The Fox",
  "Gimmy",
  "Haut Carl",
  "Henry",
  "Hondo",
  "IkBenSuperGeil",
  "iron",
  "Jbosses",
  "Jinnai",
  "Kalipulako",
  "King Panda",
  "Kismet",
  "Kuttula",
  "loke",
  "lupinthe4th",
  "machinegunqueen",
  "meesh",
  "Merk",
  "Mmiguel",
  "One Below All",
  "P4uly",
  "Platypus",
  "Pokey",
  "Rae",
  "Skykitten",
  "soso",
  "Tonyvon",
  "Trillian",
  "Trine",
  "weiwei",
  "xplodingboy",
  "Zodiac",
  "Zunneh",
  "Flavrr",
  "SouthAfi",
  "Bronze Leopard",
] as const;
